version: "3"
services:

  pgdb:
    container_name: pgdb
    image: postgres:12.2-alpine
    ports:
      - "5432:5432"
    volumes:
      #      - ./data/postgres/:/var/lib/postgresql/data
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql
    environment:
      - POSTGRES_PASSWORD=postgres

  consul:
    container_name: consul
    image: consul:1.9.16
    ports:
      - "8500:8500"

